// banks-config.js
// CONFIGURACION CENTRALIZADA DE BANCOS
// Para agregar un banco: agregar una entrada a este objeto.
// Para remover un banco: eliminar la entrada.
// Todos los archivos del proyecto leen de aqui.

const BANKS = {
    'hey-banco': {
        name: 'Hey Banco',
        fullName: 'Hey Banco México',
        accountName: 'Cuenta Hey Banco',
        iconText: 'Hey',
        color: '#1A2D4F',
        colorDark: '#0F1C2E',
        colorAccent: '#4D9EFF',
        gradient: 'linear-gradient(135deg, #0F1C2E 0%, #1A2D4F 100%)',
        identityType: 'curp',        // 'curp' | 'rfc' | 'clabe'
        cardNumber: '**** **** **** 4829',
        clabe: '058180157012345829',
        phone: '800 439 4373',
        logoHtml: '<img src="assets/banks/Hey_Banco.svg" alt="Hey Banco" style="width: 100%; height: 100%; object-fit: contain;">',
        logoHtmlCheckout: '<img src="assets/banks/Hey_Banco.svg" alt="Hey Banco" style="width: 100%; height: 100%; object-fit: contain; border-radius: 12px; background: white; padding: 4px;">',
        logoHtmlRedirect: '<img src="assets/banks/Hey_Banco.svg" alt="Hey Banco" style="width: 64px; height: 64px; object-fit: contain; background: white; padding: 4px; border-radius: 8px;">',
        logoHtmlQR: '<img src="assets/banks/Hey_Banco.svg" alt="Hey Banco" style="width: 80px; height: 80px; object-fit: contain; border-radius: 16px; background: white; padding: 6px;">',
        featured: true,
        deepLinkScheme: 'heybanco',
    },
    santander: {
        name: 'Santander',
        fullName: 'Banco Santander México',
        accountName: 'Cuenta Santander',
        iconText: 'Santander',
        color: '#EC0000',
        colorDark: '#C00000',
        colorAccent: '#FF4444',
        gradient: 'linear-gradient(135deg, #C00000 0%, #EC0000 100%)',
        identityType: 'curp',
        cardNumber: '**** **** **** 5678',
        clabe: '014180001234565678',
        phone: '55 5169 4300',
        logoHtml: '<img src="assets/banks/santa.png" alt="Santander" style="width: 32px; height: 32px; object-fit: contain;">',
        logoHtmlCheckout: '<img src="assets/banks/santa.png" alt="Santander" style="width: 100%; height: 100%; object-fit: contain; border-radius: 12px;">',
        logoHtmlRedirect: '<img src="assets/banks/santa.png" alt="Santander" style="width: 64px; height: 64px; object-fit: contain;">',
        logoHtmlQR: '<img src="assets/banks/santa.png" alt="Santander" style="width: 80px; height: 80px; object-fit: contain; border-radius: 16px;">',
        featured: false,
        deepLinkScheme: 'santander',
    },
    banamex: {
        name: 'Banamex',
        fullName: 'Citibanamex',
        accountName: 'Cuenta Banamex',
        iconText: 'Banamex',
        color: '#003B71',
        colorDark: '#002855',
        colorAccent: '#ED1C24',
        gradient: 'linear-gradient(135deg, #002855 0%, #003B71 100%)',
        identityType: 'curp',
        cardNumber: '**** **** **** 3456',
        clabe: '002180001234563456',
        phone: '55 1226 2639',
        logoHtml: '<img src="assets/banks/banamex.svg" alt="Banamex" style="width: 32px; height: 32px; object-fit: contain;">',
        logoHtmlCheckout: '<img src="assets/banks/banamex.svg" alt="Banamex" style="width: 100%; height: 100%; object-fit: contain; border-radius: 12px;">',
        logoHtmlRedirect: '<img src="assets/banks/banamex.svg" alt="Banamex" style="width: 64px; height: 64px; object-fit: contain;">',
        logoHtmlQR: '<img src="assets/banks/banamex.svg" alt="Banamex" style="width: 80px; height: 80px; object-fit: contain; border-radius: 16px;">',
        featured: false,
        deepLinkScheme: 'banamex',
    },
    bbva: {
        name: 'BBVA',
        fullName: 'BBVA México',
        accountName: 'Cuenta BBVA',
        iconText: 'BBVA',
        color: '#004481',
        colorDark: '#003366',
        colorAccent: '#0066CC',
        gradient: 'linear-gradient(135deg, #003366 0%, #004481 100%)',
        identityType: 'clabe',
        cardNumber: '**** **** **** 7890',
        clabe: '012180001234567890',
        phone: '55 5226 2663',
        logoHtml: '<svg width="32" height="32" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="40" height="40" rx="8" fill="white"/><text x="20" y="26" font-family="Arial" font-size="14" font-weight="bold" fill="#004481" text-anchor="middle">BBVA</text></svg>',
        logoHtmlCheckout: '<svg width="60" height="60" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="40" height="40" rx="8" fill="#004481"/><text x="20" y="26" font-family="Arial" font-size="14" font-weight="bold" fill="white" text-anchor="middle">BBVA</text></svg>',
        logoHtmlRedirect: '<svg width="64" height="64" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg"><text x="20" y="28" font-family="Arial" font-size="18" font-weight="bold" fill="white" text-anchor="middle">BBVA</text></svg>',
        logoHtmlQR: '<svg width="80" height="80" viewBox="0 0 80 80" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="80" height="80" rx="16" fill="#004481"/><text x="40" y="52" font-family="Arial" font-size="28" font-weight="bold" fill="white" text-anchor="middle">BBVA</text></svg>',
        featured: false,
        deepLinkScheme: 'bbva',
    },
    hsbc: {
        name: 'HSBC',
        fullName: 'HSBC México',
        accountName: 'Cuenta HSBC',
        iconText: 'HSBC',
        color: '#DB0011',
        colorDark: '#B00010',
        colorAccent: '#FF1A2F',
        gradient: 'linear-gradient(135deg, #B00010 0%, #DB0011 100%)',
        identityType: 'curp',
        cardNumber: '**** **** **** 2345',
        clabe: '021180001234562345',
        phone: '55 5721 2345',
        logoHtml: '<img src="assets/banks/hsbc.jpg" alt="HSBC" style="width: 32px; height: 32px; object-fit: contain;">',
        logoHtmlCheckout: '<img src="assets/banks/hsbc.jpg" alt="HSBC" style="width: 100%; height: 100%; object-fit: contain; border-radius: 12px;">',
        logoHtmlRedirect: '<img src="assets/banks/hsbc.jpg" alt="HSBC" style="width: 64px; height: 64px; object-fit: contain;">',
        logoHtmlQR: '<img src="assets/banks/hsbc.jpg" alt="HSBC" style="width: 80px; height: 80px; object-fit: contain; border-radius: 16px;">',
        featured: false,
        deepLinkScheme: 'hsbc',
    },
    stori: {
        name: 'Stori',
        fullName: 'Stori Card',
        accountName: 'Cuenta Stori',
        iconText: 'Stori',
        color: '#00B9AE',
        colorDark: '#009A90',
        colorAccent: '#00D4C7',
        gradient: 'linear-gradient(135deg, #009A90 0%, #00B9AE 100%)',
        identityType: 'rfc',
        cardNumber: '**** **** **** 6789',
        clabe: '646180157012346789',
        phone: '55 4161 4800',
        logoHtml: '<img src="assets/banks/stori.png" alt="Stori" style="width: 32px; height: 32px; object-fit: contain;">',
        logoHtmlCheckout: '<img src="assets/banks/stori.png" alt="Stori" style="width: 100%; height: 100%; object-fit: contain; border-radius: 12px;">',
        logoHtmlRedirect: '<img src="assets/banks/stori.png" alt="Stori" style="width: 64px; height: 64px; object-fit: contain;">',
        logoHtmlQR: '<img src="assets/banks/stori.png" alt="Stori" style="width: 80px; height: 80px; object-fit: contain; border-radius: 16px;">',
        featured: false,
        deepLinkScheme: 'stori',
    },
    banorte: {
        name: 'Banorte',
        fullName: 'Banco del Norte',
        accountName: 'Cuenta Banorte',
        iconText: 'Banorte',
        color: '#ED1C27',
        colorDark: '#C01820',
        colorAccent: '#FF3D47',
        gradient: 'linear-gradient(135deg, #C01820 0%, #ED1C27 100%)',
        identityType: 'curp',
        cardNumber: '**** **** **** 8901',
        clabe: '072180001234568901',
        phone: '55 5140 5600',
        logoHtml: '<svg width="32" height="32" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="40" height="40" rx="8" fill="white"/><text x="20" y="26" font-family="Arial" font-size="11" font-weight="bold" fill="#ED1C27" text-anchor="middle">Banorte</text></svg>',
        logoHtmlCheckout: '<svg width="60" height="60" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="40" height="40" rx="8" fill="#ED1C27"/><text x="20" y="26" font-family="Arial" font-size="11" font-weight="bold" fill="white" text-anchor="middle">Banorte</text></svg>',
        logoHtmlRedirect: '<svg width="64" height="64" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="40" height="40" rx="8" fill="#ED1C27"/><text x="20" y="26" font-family="Arial" font-size="11" font-weight="bold" fill="white" text-anchor="middle">Banorte</text></svg>',
        logoHtmlQR: '<svg width="80" height="80" viewBox="0 0 80 80" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="80" height="80" rx="16" fill="#ED1C27"/><text x="40" y="52" font-family="Arial" font-size="24" font-weight="bold" fill="white" text-anchor="middle">Banorte</text></svg>',
        featured: false,
        deepLinkScheme: 'banorte',
    },
    scotiabank: {
        name: 'Scotiabank',
        fullName: 'Scotiabank México',
        accountName: 'Cuenta Scotiabank',
        iconText: 'Scotia',
        color: '#EC1D24',
        colorDark: '#C01820',
        colorAccent: '#FF3D44',
        gradient: 'linear-gradient(135deg, #C01820 0%, #EC1D24 100%)',
        identityType: 'curp',
        cardNumber: '**** **** **** 4567',
        clabe: '044180001234564567',
        phone: '55 5123 4567',
        logoHtml: '<svg width="32" height="32" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg"><circle cx="20" cy="20" r="18" fill="white"/><circle cx="20" cy="20" r="12" stroke="#EC1D24" stroke-width="2"/></svg>',
        logoHtmlCheckout: '<svg width="60" height="60" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="40" height="40" rx="8" fill="#EC1D24"/><text x="20" y="26" font-family="Arial" font-size="10" font-weight="bold" fill="white" text-anchor="middle">Scotia</text></svg>',
        logoHtmlRedirect: '<svg width="64" height="64" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="40" height="40" rx="8" fill="#EC1D24"/><text x="20" y="26" font-family="Arial" font-size="10" font-weight="bold" fill="white" text-anchor="middle">Scotia</text></svg>',
        logoHtmlQR: '<svg width="80" height="80" viewBox="0 0 80 80" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="80" height="80" rx="16" fill="#EC1D24"/><text x="40" y="52" font-family="Arial" font-size="22" font-weight="bold" fill="white" text-anchor="middle">Scotia</text></svg>',
        featured: false,
        deepLinkScheme: 'scotiabank',
    },
    tapi: {
        name: 'TAPI',
        fullName: 'TAPI',
        accountName: 'Cuenta TAPI',
        iconText: 'TAPI',
        color: '#00c853',
        colorDark: '#00a843',
        colorAccent: '#00e676',
        gradient: 'linear-gradient(135deg, #00a843 0%, #00e676 100%)',
        identityType: 'rfc',
        cardNumber: '**** **** **** 7821',
        clabe: '646180157098765821',
        phone: '55 8765 4321',
        logoHtml: '<img src="assets/banks/tapi-Isologotipo blanco.png" alt="TAPI" style="width: 32px; height: 32px; object-fit: contain;">',
        logoHtmlCheckout: '<img src="assets/banks/tapi-Isologotipo blanco.png" alt="TAPI" style="width: 100%; height: 100%; object-fit: contain; border-radius: 12px; background: #000; padding: 8px;">',
        logoHtmlRedirect: '<img src="assets/banks/tapi-Isologotipo blanco.png" alt="TAPI" style="width: 64px; height: 64px; object-fit: contain;">',
        logoHtmlQR: '<img src="assets/banks/tapi-Isologotipo blanco.png" alt="TAPI" style="width: 80px; height: 80px; object-fit: contain; border-radius: 16px; background: #000; padding: 12px;">',
        featured: false,
        deepLinkScheme: 'tapi',
    },
};

// Helpers derivados (generados automaticamente del objeto BANKS)
// Estos mantienen retrocompatibilidad con el codigo existente en script.js
const bankNames = {};
const bankLogos = {};
const bankColors = {};
const bankIdentityRequirements = { default: 'curp' };

Object.entries(BANKS).forEach(([key, bank]) => {
    bankNames[key] = bank.name;
    bankLogos[key] = bank.logoHtmlCheckout || bank.logoHtml;
    bankColors[key] = bank.color;
    if (bank.identityType) {
        bankIdentityRequirements[key] = bank.identityType;
    }
});
